disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Â "

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "icon_rf.png"
secondaryLogo = "icon_rf.png"
description = "Grow with Nature"

[[params.author.links]]
linkedin = "https://www.linkedin.com/in/mohammedswalah"

["params.author"]
name = "Mohammed Swalah"
headline = "Grow with Nature"
image = "hero.jpg"
bio = "**An**  aspiring entrepreneur ***passionate about*** travel, technology, creativity;  **building a meaningful future through real-world experience.**"
