[[main]]
none = "none"

[[main]]
name = "My Story"
pageRef = "about"
identifier = "jTTzb3LlF1"
weight = 1

[[main]]
name = "Portfolio"
pageRef = "projects"
identifier = "1U6HPQ2cuQ"
weight = 3

[[main]]
name = "Blog"
pageRef = "posts"
identifier = "n8EjRg1Rsq"
weight = 2

[[main]]
name = "Gallery"
pageRef = "gallery"
identifier = "FyLDX9O1qW"
weight = 4

[[main]]
name = "Get in Touch"
pageRef = "contact"
identifier = "d35l3UUuBl"
weight = 5

[[footer]]
none = "none"

[[footer]]
name = "About"
pageRef = "about"
identifier = "9BRDy63t7i"
weight = 1

[[footer]]
name = "Portfolio"
pageRef = "projects"
identifier = "vMiDYn4MCz"
weight = 3

[[footer]]
name = "Blog"
pageRef = "posts"
identifier = "YRjZDyyZMv"
weight = 2

[[footer]]
name = "Gallery"
pageRef = "gallery"
identifier = "ke1fTALYpG"
weight = 4

[[footer]]
name = "Get in Touch"
pageRef = "contact"
identifier = "OAlm6r4eot"
weight = 5
